# Generated by Django 3.1.3 on 2020-11-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('new', 'New'), ('in progress', 'In Progress'), ('invalid', 'Invalid')], default='new', max_length=20),
        ),
    ]
